### ISSUE TITLE
branch : Inji - HTML approval pages

### ISSUE THREAD

**Issue by inji-yeon** [Witty-Puppy/Frontend-html#16]
##Description 
Setting structure for the approval pages and create HTML.

##To-do

- [x] Make sub-sidebar for the approval pages.
- [x] Create for selecting approval form and link it with each forms.
  - [x] Forms: on leave, overtime, work away, business trip, usage of software.
- [x] Make approval inbox, outbox, view pages.
  - [x] Inbox section: documents on process, finished list, rejected list, retrieved list, and temporary savings.
  - [x] Outbox section: awaiting list, approved list, documents for represent approval.
  - [x] View section: documents that can view.
- [x] Make page for writing document and setting approval line.
  - [x] Show preview of approval form.
  - [x] Show group chart and can set group line.
